In [156]:
import pandas as pd
#Api Banco Central de Chile
!pip install bcchapi
import bcchapi
import requests
import zipfile
import tempfile
import os
from io import BytesIO
import time
from tqdm import tqdm
import itertools

Requirement already satisfied: bcchapi in c:\users\claud\miniconda3\lib\site-packages (1.1.2)
Requirement already satisfied: pandas>=1.2.0 in c:\users\claud\miniconda3\lib\site-packages (from bcchapi) (2.2.3)
Requirement already satisfied: requests>=2.0.1 in c:\users\claud\miniconda3\lib\site-packages (from bcchapi) (2.32.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\claud\miniconda3\lib\site-packages (from pandas>=1.2.0->bcchapi) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\claud\miniconda3\lib\site-packages (from pandas>=1.2.0->bcchapi) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\claud\miniconda3\lib\site-packages (from pandas>=1.2.0->bcchapi) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\claud\miniconda3\lib\site-packages (from pandas>=1.2.0->bcchapi) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\claud\miniconda3\lib\site-packages (from requests>=2.0.1->bcchapi) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\claud\miniconda3\lib\site-packages (from requests>=2.0.1->bcchapi) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\claud\miniconda3\lib\site-packages (from requests>=2.0.1->bcchapi) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\claud\miniconda3\lib\site-packages (from requests>=2.0.1->bcchapi) (2025.10.5)
Requirement already satisfied: six>=1.5 in c:\users\claud\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->bcchapi) (1.17.0)

### Sociedad Hipotecaria Federal (Mexico)

In [ ]:
shf=pd.read_excel("https://www.gob.mx/cms/uploads/attachment/file/1055836/Indice_SHF_datos_abiertos_4_trim_2025.xlsx")
shf.columns=shf.columns.str.lower()

shf=shf[["global", "estado","municipio", "trimestre", "año","indice"]]
#Rename
shf=shf.rename(columns={"global":"variable", "estado":"state", "municipio":"municipality", "trimestre":"quarter", "año":"year", "indice":"value"})
shf['date'] = pd.PeriodIndex(
    year=shf['year'],
    quarter=shf['quarter'],
    freq='Q'
).to_timestamp()
#Add country
shf["country"]="Mexico"
#add source
shf["source"]="Sociedad Hipotecaria Federal"
shf["base_year"]=2017
shf['var_type'] = 'index'
shf=shf[["country", "state", "municipality", "date", "variable", "value","var_type", "source", "base_year"]]

shf

C:\Users\claud\AppData\Local\Temp\ipykernel_51420\904601658.py:7: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  shf['date'] = pd.PeriodIndex(

,country,state,municipality,date,variable,value,var_type,source,base_year
0,Mexico,NaN,NaN,2005-01-01,Nacional,48.47,index,Sociedad Hipotecaria Federal,2017
1,Mexico,NaN,NaN,2005-01-01,Nueva,48.20,index,Sociedad Hipotecaria Federal,2017
2,Mexico,NaN,NaN,2005-01-01,Usada,48.76,index,Sociedad Hipotecaria Federal,2017
3,Mexico,NaN,NaN,2005-01-01,Casa sola,49.08,index,Sociedad Hipotecaria Federal,2017
4,Mexico,NaN,NaN,2005-01-01,Casa en condominio - depto.,47.79,index,Sociedad Hipotecaria Federal,2017
...,...,...,...,...,...,...,...,...,...
10159,Mexico,Veracruz,Veracruz,2025-10-01,NaN,194.41,index,Sociedad Hipotecaria Federal,2017
10160,Mexico,Yucatán,Kanasín,2025-10-01,NaN,206.26,index,Sociedad Hipotecaria Federal,2017
10161,Mexico,Yucatán,Mérida,2025-10-01,NaN,209.36,index,Sociedad Hipotecaria Federal,2017
10162,Mexico,Zacatecas,Guadalupe,2025-10-01,NaN,180.85,index,Sociedad Hipotecaria Federal,2017
10163,Mexico,Zacatecas,Zacatecas,2025-10-01,NaN,175.71,index,Sociedad Hipotecaria Federal,2017

### Banco Central de Chile (Chile)

In [57]:
creds = {}

with open("C:\\Users\\claud\\Documents\\credenciales_bcc.txt", "r") as f:
    for linea in f:
        clave, valor = linea.strip().split("=")
        creds[clave] = valor

usuario = creds["usuario"]
password = creds["password"]

credenciales = bcchapi.Siete(usuario, password)

In [84]:
tabla_ipv=credenciales.cuadro(
  series=["F034.IPV.FLU.BCCH.2008.0.T", 
          "F034.IPVC.FLU.BCCH.2008.0.T",
          "F034.IPVCNEW.FLU.BCCH.2008.0.T",
          "F034.IPVCUSED.FLU.BCCH.2008.0.T",
          "F034.IPVD.FLU.BCCH.2008.0.T", 
          "F034.IPVDNEW.FLU.BCCH.2008.0.T",
          "F034.IPVDUSED.FLU.BCCH.2008.0.T",
          "F034.IVPZ1.FLU.BCCH.2008.0.T",
          "F034.IPVZ2.FLU.BCCH.2008.0.T",
          "F034.IPVZ3.FLU.BCCH.2008.0.T",
          "F034.IPVZ4.FLU.BCCH.2008.0.T"
        
          ],
  nombres = ["ipv_general", 
             "ipv_houses", 
             "ipv_new_houses",
             "ipv_used_houses",
              "ipv_apartments",
              "ipv_new_apartments",
              "ipv_used_apartments",
              "ipv_north_zone",
              "ipv_central_zone",
              "ipv_south_zone",
              "ipv_metropolitan_region"
             
             
             
             
             
             ],
  desde="2001-01-01",
  hasta="2025-12-31"
)
tabla_ipv = tabla_ipv.reset_index().rename(columns={'index': 'date'})
tabla_ipv = tabla_ipv.melt(
    id_vars='date',          
    var_name='variable',     
    value_name='value'       
)
tabla_ipv["country"]="Chile"
tabla_ipv["source"]="Banco Central de Chile"
tabla_ipv["base_year"]=2008
tabla_ipv['var_type'] = 'index'
tabla_ipv

,date,variable,value,country,source,base_year,var_type
0,2002-01-01,ipv_general,79.819860,Chile,Banco Central de Chile,2008,index
1,2002-04-01,ipv_general,82.868177,Chile,Banco Central de Chile,2008,index
2,2002-07-01,ipv_general,83.698377,Chile,Banco Central de Chile,2008,index
3,2002-10-01,ipv_general,83.196206,Chile,Banco Central de Chile,2008,index
4,2003-01-01,ipv_general,82.737826,Chile,Banco Central de Chile,2008,index
...,...,...,...,...,...,...,...
1040,2024-07-01,ipv_metropolitan_region,228.655103,Chile,Banco Central de Chile,2008,index
1041,2024-10-01,ipv_metropolitan_region,230.045391,Chile,Banco Central de Chile,2008,index
1042,2025-01-01,ipv_metropolitan_region,232.929202,Chile,Banco Central de Chile,2008,index
1043,2025-04-01,ipv_metropolitan_region,234.278572,Chile,Banco Central de Chile,2008,index
1044,2025-07-01,ipv_metropolitan_region,235.416575,Chile,Banco Central de Chile,2008,index

#### Banco de la República (Colombia)

In [85]:
url="https://suameca.banrep.gov.co/estadisticas-economicas-back/rest/estadisticaEconomicaRestService/exportarReporteExcel?reportPath=/shared/Estadisticas_Banco_de_la_Republica/1_Precios_e_Inflacion/5_Indice_de_precios_de_la_vivienda/2_IPVU_Indice_de_precios_de_la_vivienda_usada/2_IPVU_Indice_nominal_y_real_periodicidad_trimestral_iqy&formato=csv"

In [86]:
ipvu=pd.read_csv(url)
#delete first column
ipvu=ipvu.drop(ipvu.columns[0], axis=1)
#rename columns
ipvu=ipvu.rename(columns={"Fecha":"date", "índice nominal":"ipvu_nominal", "Índice real":"ipvu_real"})
ipvu = ipvu.melt(
    id_vars='date',          
    var_name='variable',     
    value_name='index'       
)
ipvu["country"]="Colombia"
ipvu["source"]="Banco de la República Colombia"
ipvu["base_year"]=1990
ipvu['var_type'] = 'index'
ipvu

,date,variable,index,country,source,base_year,var_type
0,1988-03-31 00:00:00,Índice nominal,55.602458,Colombia,Banco de la República Colombia,1990,index
1,1988-06-30 00:00:00,Índice nominal,54.278016,Colombia,Banco de la República Colombia,1990,index
2,1988-09-30 00:00:00,Índice nominal,64.241675,Colombia,Banco de la República Colombia,1990,index
3,1988-12-31 00:00:00,Índice nominal,63.775098,Colombia,Banco de la República Colombia,1990,index
4,1989-03-31 00:00:00,Índice nominal,72.866472,Colombia,Banco de la República Colombia,1990,index
...,...,...,...,...,...,...,...
297,2024-09-30 00:00:00,ipvu_real,125.463418,Colombia,Banco de la República Colombia,1990,index
298,2024-12-31 00:00:00,ipvu_real,123.697949,Colombia,Banco de la República Colombia,1990,index
299,2025-03-31 00:00:00,ipvu_real,124.081023,Colombia,Banco de la República Colombia,1990,index
300,2025-06-30 00:00:00,ipvu_real,128.251738,Colombia,Banco de la República Colombia,1990,index
301,2025-09-30 00:00:00,ipvu_real,128.458473,Colombia,Banco de la República Colombia,1990,index

In [121]:

cookies = {
    'ASP.NET_SessionId': 'nlozsogjk5ww4cqxqg1jpxnv',
    '__RequestVerificationToken': '7BCLDlTekEDtACKollit9w2ymsNm-OL0yPRKX3spSLP-pJTX4PdkAsQ7aPJcGZCTl6TAKfCh62Wt8ys23vrd99uGhTLvyFo4PkdeCHft9qU1',
    'ROUTEID': '.5',
    '_gcl_au': '1.1.528231028.1775600956',
    '_gid': 'GA1.3.259430437.1775789301',
    'AMP_MKTG_8f1ede8e9c': 'JTdCJTdE',
    '_ga': 'GA1.1.1370069149.1775600956',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJiNTA0MDhmZS0zZDdlLTRmYmItYjNiNi00OGQzMWQxZTEwYmElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzc1NzkzNTg5OTk3JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlMkMlMjJsYXN0RXZlbnRUaW1lJTIyJTNBMTc3NTc5MzU5MDAwNiU3RA==',
    '_ga_WN7SEBCDBR': 'GS2.1.s1775793590$o5$g1$t1775794876$j60$l0$h0',
}

headers = {
    'accept': '*/*',
    'accept-language': 'es-US,es-419;q=0.9,es;q=0.8',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'origin': 'https://www.fipe.org.br',
    'priority': 'u=1, i',
    'referer': 'https://www.fipe.org.br/en-us/indexes-and-indicators/fipezap/',
    'sec-ch-ua': '"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36',
    'x-requested-with': 'XMLHttpRequest',
    # 'cookie': 'ASP.NET_SessionId=nlozsogjk5ww4cqxqg1jpxnv; __RequestVerificationToken=7BCLDlTekEDtACKollit9w2ymsNm-OL0yPRKX3spSLP-pJTX4PdkAsQ7aPJcGZCTl6TAKfCh62Wt8ys23vrd99uGhTLvyFo4PkdeCHft9qU1; ROUTEID=.5; _gcl_au=1.1.528231028.1775600956; _gid=GA1.3.259430437.1775789301; AMP_MKTG_8f1ede8e9c=JTdCJTdE; _ga=GA1.1.1370069149.1775600956; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJiNTA0MDhmZS0zZDdlLTRmYmItYjNiNi00OGQzMWQxZTEwYmElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzc1NzkzNTg5OTk3JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlMkMlMjJsYXN0RXZlbnRUaW1lJTIyJTNBMTc3NTc5MzU5MDAwNiU3RA==; _ga_WN7SEBCDBR=GS2.1.s1775793590$o5$g1$t1775794876$j60$l0$h0',
}

data = {
    'codigoTipo': '2',
    'codigoInfo': '2',
}

response1 = requests.post('https://www.fipe.org.br/IndicesConsulta-FipeZapRegiao', cookies=cookies, headers=headers, data=data)

In [122]:
regions1=pd.DataFrame(response1.json())
regions1.columns=regions1.columns.str.lower()
#sort by codigo
regions1=regions1.sort_values(by="codigo")
regions1

    codigo                     nome
52       2                São Paulo
39       3           Rio de Janeiro
4        4           Belo Horizonte
15       5         Distrito Federal
37       6                   Recife
18       7                Fortaleza
40       8                 Salvador
42       9              Santo André
44      10    São Bernardo do Campo
45      11       São Caetano do Sul
31      12                  Niterói
56      13                  Vitória
55      14               Vila Velha
35      15             Porto Alegre
13      16                 Curitiba
17      17            Florianópolis
16      18                  FipeZap
11      19                 Contagem
7       20                 Campinas
33      21                   Osasco
21      22                Guarulhos
43      23                   Santos
20      24                  Guarujá
53      25              São Vicente
36      26             Praia Grande
19      27                  Goiânia
2       29                  Barueri
14      30                  Diadema
38      31           Ribeirão Preto
47      32    São José do Rio Preto
48      33      São José dos Campos
5       34                    Betim
9       35                   Canoas
10      36            Caxias do Sul
32      37            Novo Hamburgo
34      38                  Pelotas
41      39              Santa Maria
50      40             São Leopoldo
27      41                 Londrina
49      42     São José dos Pinhais
1       43       Balneário Camboriú
6       44                 Blumenau
22      45                   Itajaí
23      46                  Itapema
26      47                Joinville
46      48                 São José
25      49              João Pessoa
8       50             Campo Grande
28      51                   Maceió
29      52                   Manaus
24      53  Jaboatão dos Guararapes
12      54                   Cuiabá
0       55                  Aracaju
30      56                    Natal
51      57                 São Luís
54      58                 Teresina
3       59                    Belém

In [123]:
cookies = {
    'ASP.NET_SessionId': 'nlozsogjk5ww4cqxqg1jpxnv',
    '__RequestVerificationToken': '7BCLDlTekEDtACKollit9w2ymsNm-OL0yPRKX3spSLP-pJTX4PdkAsQ7aPJcGZCTl6TAKfCh62Wt8ys23vrd99uGhTLvyFo4PkdeCHft9qU1',
    'ROUTEID': '.5',
    '_gcl_au': '1.1.528231028.1775600956',
    '_gid': 'GA1.3.259430437.1775789301',
    'AMP_MKTG_8f1ede8e9c': 'JTdCJTdE',
    '_ga': 'GA1.1.1370069149.1775600956',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJiNTA0MDhmZS0zZDdlLTRmYmItYjNiNi00OGQzMWQxZTEwYmElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzc1NzkzNTg5OTk3JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlMkMlMjJsYXN0RXZlbnRUaW1lJTIyJTNBMTc3NTc5MzU5MDAwNiU3RA==',
    '_ga_WN7SEBCDBR': 'GS2.1.s1775793590$o5$g1$t1775795823$j60$l0$h0',
}

headers = {
    'accept': '*/*',
    'accept-language': 'es-US,es-419;q=0.9,es;q=0.8',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'origin': 'https://www.fipe.org.br',
    'priority': 'u=1, i',
    'referer': 'https://www.fipe.org.br/en-us/indexes-and-indicators/fipezap/',
    'sec-ch-ua': '"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36',
    'x-requested-with': 'XMLHttpRequest',
    # 'cookie': 'ASP.NET_SessionId=nlozsogjk5ww4cqxqg1jpxnv; __RequestVerificationToken=7BCLDlTekEDtACKollit9w2ymsNm-OL0yPRKX3spSLP-pJTX4PdkAsQ7aPJcGZCTl6TAKfCh62Wt8ys23vrd99uGhTLvyFo4PkdeCHft9qU1; ROUTEID=.5; _gcl_au=1.1.528231028.1775600956; _gid=GA1.3.259430437.1775789301; AMP_MKTG_8f1ede8e9c=JTdCJTdE; _ga=GA1.1.1370069149.1775600956; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJiNTA0MDhmZS0zZDdlLTRmYmItYjNiNi00OGQzMWQxZTEwYmElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzc1NzkzNTg5OTk3JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlMkMlMjJsYXN0RXZlbnRUaW1lJTIyJTNBMTc3NTc5MzU5MDAwNiU3RA==; _ga_WN7SEBCDBR=GS2.1.s1775793590$o5$g1$t1775795823$j60$l0$h0',
}

data = {
    'codigoTipo': '1',
    'codigoInfo': '2',
}

response2 = requests.post('https://www.fipe.org.br/IndicesConsulta-FipeZapRegiao', cookies=cookies, headers=headers, data=data)

In [124]:
regions2=pd.DataFrame(response2.json())
regions2.columns=regions2.columns.str.lower()
#sort by codigo
regions2=regions2.sort_values(by="codigo")
regions2

    codigo                   nome
34       2              São Paulo
25       3         Rio de Janeiro
3        4         Belo Horizonte
8        5       Distrito Federal
23       6                 Recife
11       7              Fortaleza
26       8               Salvador
27       9            Santo André
29      10  São Bernardo do Campo
19      12                Niterói
36      13                Vitória
21      15           Porto Alegre
7       16               Curitiba
10      17          Florianópolis
4       20               Campinas
13      22              Guarulhos
28      23                 Santos
22      26           Praia Grande
12      27                Goiânia
9       28        FipeZap Locação
1       29                Barueri
24      31         Ribeirão Preto
31      32  São José do Rio Preto
32      33    São José dos Campos
20      38                Pelotas
15      47              Joinville
30      48               São José
14      49            João Pessoa
5       50           Campo Grande
16      51                 Maceió
17      52                 Manaus
6       54                 Cuiabá
0       55                Aracaju
18      56                  Natal
33      57               São Luís
35      58               Teresina
2       59                  Belém

In [142]:
#Concat regions1 and regions2 and drop duplicates
regions=pd.concat([regions1, regions2], ignore_index=True).drop_duplicates()
#sort by codigo
regions=regions.sort_values(by="codigo")
regions

    codigo                     nome
0        2                São Paulo
1        3           Rio de Janeiro
2        4           Belo Horizonte
3        5         Distrito Federal
4        6                   Recife
5        7                Fortaleza
6        8                 Salvador
7        9              Santo André
8       10    São Bernardo do Campo
9       11       São Caetano do Sul
10      12                  Niterói
11      13                  Vitória
12      14               Vila Velha
13      15             Porto Alegre
14      16                 Curitiba
15      17            Florianópolis
16      18                  FipeZap
17      19                 Contagem
18      20                 Campinas
19      21                   Osasco
20      22                Guarulhos
21      23                   Santos
22      24                  Guarujá
23      25              São Vicente
24      26             Praia Grande
25      27                  Goiânia
76      28          FipeZap Locação
26      29                  Barueri
27      30                  Diadema
28      31           Ribeirão Preto
29      32    São José do Rio Preto
30      33      São José dos Campos
31      34                    Betim
32      35                   Canoas
33      36            Caxias do Sul
34      37            Novo Hamburgo
35      38                  Pelotas
36      39              Santa Maria
37      40             São Leopoldo
38      41                 Londrina
39      42     São José dos Pinhais
40      43       Balneário Camboriú
41      44                 Blumenau
42      45                   Itajaí
43      46                  Itapema
44      47                Joinville
45      48                 São José
46      49              João Pessoa
47      50             Campo Grande
48      51                   Maceió
49      52                   Manaus
50      53  Jaboatão dos Guararapes
51      54                   Cuiabá
52      55                  Aracaju
53      56                    Natal
54      57                 São Luís
55      58                 Teresina
56      59                    Belém

In [ ]:
def get_fipezap(tipo, region, dormitorios):

    url = (
        "https://www.fipe.org.br/IndicesConsulta-FipeZapPesquisa"
        f"?tipo={tipo}&regiao={region}&info=2&dormitorio={dormitorios}"
    )

    headers = {"User-Agent": "Mozilla/5.0"}

    r = requests.get(url, headers=headers, timeout=10)
    r.raise_for_status()

    data = r.json()
    df = pd.DataFrame(data)

    if df.empty:
        return None

    #Drop last column
    df = df.loc[:, ~df.columns.str.contains("Variacao", case=False)]

    value_col = [c for c in df.columns if c not in [
        'Ano', 'Mes', 'CodigoDormitorio'
    ]][0]

    # rename
    df = df.rename(columns={
        "Ano": "year",
        "Mes": "month",
        "CodigoDormitorio": "rooms",
        value_col: "value"
    })

    # date
    df["date"] = pd.to_datetime(dict(year=df.year, month=df.month, day=1))

    # dorms
    room_map = {
        1: 'total',
        2: '1',
        3: '2',
        4: '3',
        5: '4+'
    }

    df['rooms'] = df['rooms'].map(room_map)

    # metadata
    df['region_code'] = region
    df['variable'] = 'price_sale_index' if tipo == 2 else 'price_rent_index'
    df['var_type'] = 'index'
    df['country'] = 'Brazil'
    df['source'] = 'FIPEZAP'

    return df[['date','region_code','rooms','variable','value','var_type','country','source']]

#Loop

def load_fipezap_all(df_regiones):

    tipos = [1, 2]        
    dorms = [1,2,3,4,5]

    dfs = []
    errors = 0

    # combinaciones completas
    combos = list(itertools.product(df_regiones['codigo'], tipos, dorms))

    for region, tipo, dorm in tqdm(combos, desc="Downloading FIPEZAP"):

        try:
            df_tmp = get_fipezap(tipo, region, dorm)

            if df_tmp is not None:
                dfs.append(df_tmp)

            time.sleep(0.2)  

        except Exception as e:
            errors += 1
            print(f"\nERROR region={region} tipo={tipo} dorm={dorm} -> {e}")

    # concat
    df_final = pd.concat(dfs, ignore_index=True)

    # merge with regions
    df_final = df_final.merge(
        df_regiones,
        left_on='region_code',
        right_on='codigo',
        how='left'
    )

    # city
    df_final = df_final.rename(columns={'nome': 'city'})

    # 
    df_final = df_final[[
        'date','country','region_code','city',
        'rooms','variable','value',
        'var_type','source'
    ]]

    print(f"\nErrores totales: {errors}")

    return df_final

In [159]:
# Get data
df_fipezap = load_fipezap_all(regions)

df_fipezap.head()

Downloading FIPEZAP:   9%|▉         | 52/580 [01:01<10:23,  1.18s/it]

ERROR region=7 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:   9%|▉         | 53/580 [01:02<09:46,  1.11s/it]

ERROR region=7 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:   9%|▉         | 54/580 [01:04<09:43,  1.11s/it]

ERROR region=7 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:   9%|▉         | 55/580 [01:05<09:24,  1.08s/it]

ERROR region=7 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  10%|▉         | 57/580 [01:07<09:38,  1.11s/it]

ERROR region=7 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  12%|█▏        | 72/580 [01:26<10:49,  1.28s/it]

ERROR region=9 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  13%|█▎        | 73/580 [01:27<10:12,  1.21s/it]

ERROR region=9 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  13%|█▎        | 74/580 [01:28<08:55,  1.06s/it]

ERROR region=9 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  13%|█▎        | 75/580 [01:29<08:56,  1.06s/it]

ERROR region=9 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  16%|█▌        | 91/580 [01:49<09:34,  1.18s/it]

ERROR region=11 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  16%|█▌        | 92/580 [01:50<09:04,  1.12s/it]

ERROR region=11 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  16%|█▌        | 93/580 [01:51<09:04,  1.12s/it]

ERROR region=11 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  16%|█▌        | 94/580 [01:52<08:43,  1.08s/it]

ERROR region=11 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  16%|█▋        | 95/580 [01:53<08:38,  1.07s/it]

ERROR region=11 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  18%|█▊        | 102/580 [02:03<10:12,  1.28s/it]

ERROR region=12 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  18%|█▊        | 103/580 [02:04<10:12,  1.28s/it]

ERROR region=12 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  18%|█▊        | 104/580 [02:05<10:11,  1.29s/it]

ERROR region=12 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  18%|█▊        | 105/580 [02:06<09:26,  1.19s/it]

ERROR region=12 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  19%|█▉        | 112/580 [02:15<08:59,  1.15s/it]

ERROR region=13 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  19%|█▉        | 113/580 [02:16<09:05,  1.17s/it]

ERROR region=13 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  20%|█▉        | 114/580 [02:17<08:34,  1.10s/it]

ERROR region=13 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  20%|█▉        | 115/580 [02:18<08:52,  1.15s/it]

ERROR region=13 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  21%|██        | 121/580 [02:27<10:15,  1.34s/it]

ERROR region=14 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  21%|██        | 122/580 [02:27<08:56,  1.17s/it]

ERROR region=14 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  21%|██        | 123/580 [02:28<08:35,  1.13s/it]

ERROR region=14 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  21%|██▏       | 124/580 [02:30<08:43,  1.15s/it]

ERROR region=14 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  22%|██▏       | 125/580 [02:31<09:02,  1.19s/it]

ERROR region=14 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  26%|██▌       | 152/580 [03:05<07:25,  1.04s/it]

ERROR region=17 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  26%|██▋       | 153/580 [03:06<06:56,  1.03it/s]

ERROR region=17 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  27%|██▋       | 154/580 [03:07<06:08,  1.16it/s]

ERROR region=17 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  27%|██▋       | 155/580 [03:08<06:06,  1.16it/s]

ERROR region=17 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  28%|██▊       | 161/580 [03:13<06:07,  1.14it/s]

ERROR region=18 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  28%|██▊       | 162/580 [03:14<06:01,  1.16it/s]

ERROR region=18 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  28%|██▊       | 163/580 [03:15<06:00,  1.16it/s]

ERROR region=18 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  28%|██▊       | 164/580 [03:16<06:09,  1.13it/s]

ERROR region=18 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  28%|██▊       | 165/580 [03:17<06:25,  1.08it/s]

ERROR region=18 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  29%|██▉       | 171/580 [03:23<06:34,  1.04it/s]

ERROR region=19 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  30%|██▉       | 172/580 [03:24<06:17,  1.08it/s]

ERROR region=19 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  30%|██▉       | 173/580 [03:25<06:43,  1.01it/s]

ERROR region=19 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  30%|███       | 174/580 [03:26<05:48,  1.16it/s]

ERROR region=19 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  30%|███       | 175/580 [03:27<05:52,  1.15it/s]

ERROR region=19 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  31%|███       | 177/580 [03:29<06:16,  1.07it/s]

ERROR region=19 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  33%|███▎      | 191/580 [03:43<06:21,  1.02it/s]

ERROR region=21 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  33%|███▎      | 192/580 [03:44<06:05,  1.06it/s]

ERROR region=21 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  33%|███▎      | 193/580 [03:45<05:58,  1.08it/s]

ERROR region=21 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  33%|███▎      | 194/580 [03:46<05:49,  1.11it/s]

ERROR region=21 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  34%|███▎      | 195/580 [03:46<05:09,  1.24it/s]

ERROR region=21 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  34%|███▍      | 197/580 [03:48<05:32,  1.15it/s]

ERROR region=21 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  35%|███▍      | 202/580 [03:52<05:01,  1.25it/s]

ERROR region=22 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  35%|███▌      | 203/580 [03:53<05:04,  1.24it/s]

ERROR region=22 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  35%|███▌      | 204/580 [03:54<05:07,  1.22it/s]

ERROR region=22 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  35%|███▌      | 205/580 [03:54<04:37,  1.35it/s]

ERROR region=22 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  38%|███▊      | 221/580 [04:11<05:23,  1.11it/s]

ERROR region=24 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  38%|███▊      | 222/580 [04:12<05:16,  1.13it/s]

ERROR region=24 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  38%|███▊      | 223/580 [04:12<05:07,  1.16it/s]

ERROR region=24 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  39%|███▊      | 224/580 [04:13<05:06,  1.16it/s]

ERROR region=24 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  39%|███▉      | 225/580 [04:14<05:05,  1.16it/s]

ERROR region=24 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  40%|███▉      | 231/580 [04:21<06:43,  1.16s/it]

ERROR region=25 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  40%|████      | 232/580 [04:22<06:44,  1.16s/it]

ERROR region=25 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  40%|████      | 233/580 [04:23<06:39,  1.15s/it]

ERROR region=25 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  40%|████      | 234/580 [04:25<06:34,  1.14s/it]

ERROR region=25 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  41%|████      | 235/580 [04:26<06:17,  1.09s/it]

ERROR region=25 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  42%|████▏     | 242/580 [04:35<06:50,  1.22s/it]

ERROR region=26 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  42%|████▏     | 243/580 [04:36<06:48,  1.21s/it]

ERROR region=26 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  42%|████▏     | 244/580 [04:37<06:22,  1.14s/it]

ERROR region=26 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  42%|████▏     | 245/580 [04:38<06:19,  1.13s/it]

ERROR region=26 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  43%|████▎     | 252/580 [04:47<07:09,  1.31s/it]

ERROR region=27 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  44%|████▎     | 253/580 [04:48<06:49,  1.25s/it]

ERROR region=27 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  44%|████▍     | 254/580 [04:49<06:31,  1.20s/it]

ERROR region=27 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  44%|████▍     | 255/580 [04:50<05:43,  1.06s/it]

ERROR region=27 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  46%|████▌     | 266/580 [05:02<05:16,  1.01s/it]

ERROR region=28 tipo=2 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  46%|████▌     | 267/580 [05:03<05:06,  1.02it/s]

ERROR region=28 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  46%|████▌     | 268/580 [05:03<04:52,  1.07it/s]

ERROR region=28 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  46%|████▋     | 269/580 [05:04<04:41,  1.11it/s]

ERROR region=28 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  47%|████▋     | 270/580 [05:05<04:33,  1.13it/s]

ERROR region=28 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  47%|████▋     | 272/580 [05:07<05:15,  1.02s/it]

ERROR region=29 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  47%|████▋     | 273/580 [05:09<05:25,  1.06s/it]

ERROR region=29 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  47%|████▋     | 274/580 [05:10<05:22,  1.05s/it]

ERROR region=29 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  47%|████▋     | 275/580 [05:11<05:34,  1.10s/it]

ERROR region=29 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  48%|████▊     | 277/580 [05:13<05:42,  1.13s/it]

ERROR region=29 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  48%|████▊     | 278/580 [05:14<05:45,  1.14s/it]

ERROR region=29 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  48%|████▊     | 279/580 [05:15<05:35,  1.11s/it]

ERROR region=29 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  48%|████▊     | 280/580 [05:17<05:30,  1.10s/it]

ERROR region=29 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  48%|████▊     | 281/580 [05:18<05:22,  1.08s/it]

ERROR region=30 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  49%|████▊     | 282/580 [05:19<05:21,  1.08s/it]

ERROR region=30 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  49%|████▉     | 283/580 [05:20<05:13,  1.05s/it]

ERROR region=30 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  49%|████▉     | 284/580 [05:21<05:15,  1.07s/it]

ERROR region=30 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  49%|████▉     | 285/580 [05:22<05:22,  1.09s/it]

ERROR region=30 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  49%|████▉     | 287/580 [05:25<05:53,  1.21s/it]

ERROR region=30 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  50%|████▉     | 288/580 [05:26<05:39,  1.16s/it]

ERROR region=30 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  50%|████▉     | 289/580 [05:27<05:23,  1.11s/it]

ERROR region=30 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  50%|█████     | 290/580 [05:28<05:24,  1.12s/it]

ERROR region=30 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  50%|█████     | 292/580 [05:30<05:27,  1.14s/it]

ERROR region=31 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  51%|█████     | 293/580 [05:31<05:29,  1.15s/it]

ERROR region=31 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  51%|█████     | 294/580 [05:32<04:54,  1.03s/it]

ERROR region=31 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  51%|█████     | 295/580 [05:33<04:56,  1.04s/it]

ERROR region=31 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  52%|█████▏    | 302/580 [05:41<05:13,  1.13s/it]

ERROR region=32 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  52%|█████▏    | 303/580 [05:42<04:47,  1.04s/it]

ERROR region=32 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  52%|█████▏    | 304/580 [05:43<04:46,  1.04s/it]

ERROR region=32 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  53%|█████▎    | 305/580 [05:44<04:45,  1.04s/it]

ERROR region=32 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  53%|█████▎    | 307/580 [05:46<04:32,  1.00it/s]

ERROR region=32 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  53%|█████▎    | 308/580 [05:47<04:17,  1.06it/s]

ERROR region=32 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  53%|█████▎    | 309/580 [05:48<04:09,  1.09it/s]

ERROR region=32 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  53%|█████▎    | 310/580 [05:49<04:01,  1.12it/s]

ERROR region=32 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  54%|█████▍    | 312/580 [05:50<04:03,  1.10it/s]

ERROR region=33 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  54%|█████▍    | 313/580 [05:51<03:58,  1.12it/s]

ERROR region=33 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  54%|█████▍    | 314/580 [05:52<03:54,  1.13it/s]

ERROR region=33 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  54%|█████▍    | 315/580 [05:53<03:50,  1.15it/s]

ERROR region=33 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  55%|█████▍    | 317/580 [05:55<03:41,  1.19it/s]

ERROR region=33 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  55%|█████▍    | 318/580 [05:55<03:39,  1.19it/s]

ERROR region=33 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  55%|█████▌    | 319/580 [05:56<03:38,  1.20it/s]

ERROR region=33 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  55%|█████▌    | 320/580 [05:57<03:41,  1.17it/s]

ERROR region=33 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  55%|█████▌    | 321/580 [05:58<04:08,  1.04it/s]

ERROR region=34 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  56%|█████▌    | 322/580 [05:59<04:15,  1.01it/s]

ERROR region=34 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  56%|█████▌    | 323/580 [06:01<04:29,  1.05s/it]

ERROR region=34 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  56%|█████▌    | 324/580 [06:02<04:38,  1.09s/it]

ERROR region=34 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  56%|█████▌    | 325/580 [06:03<04:42,  1.11s/it]

ERROR region=34 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  56%|█████▋    | 327/580 [06:05<04:40,  1.11s/it]

ERROR region=34 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  57%|█████▋    | 328/580 [06:06<04:33,  1.09s/it]

ERROR region=34 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  57%|█████▋    | 329/580 [06:07<04:22,  1.05s/it]

ERROR region=34 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  57%|█████▋    | 330/580 [06:08<04:07,  1.01it/s]

ERROR region=34 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  57%|█████▋    | 331/580 [06:09<03:54,  1.06it/s]

ERROR region=35 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  57%|█████▋    | 332/580 [06:10<03:43,  1.11it/s]

ERROR region=35 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  57%|█████▋    | 333/580 [06:11<03:52,  1.06it/s]

ERROR region=35 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  58%|█████▊    | 334/580 [06:11<03:33,  1.15it/s]

ERROR region=35 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  58%|█████▊    | 335/580 [06:12<03:26,  1.19it/s]

ERROR region=35 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  58%|█████▊    | 337/580 [06:15<03:58,  1.02it/s]

ERROR region=35 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  58%|█████▊    | 338/580 [06:16<04:05,  1.01s/it]

ERROR region=35 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  58%|█████▊    | 339/580 [06:17<04:08,  1.03s/it]

ERROR region=35 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  59%|█████▊    | 340/580 [06:18<04:14,  1.06s/it]

ERROR region=35 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  59%|█████▉    | 341/580 [06:19<04:19,  1.09s/it]

ERROR region=36 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  59%|█████▉    | 342/580 [06:20<04:19,  1.09s/it]

ERROR region=36 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  59%|█████▉    | 343/580 [06:21<03:57,  1.00s/it]

ERROR region=36 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  59%|█████▉    | 344/580 [06:22<03:30,  1.12it/s]

ERROR region=36 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  59%|█████▉    | 345/580 [06:22<03:28,  1.13it/s]

ERROR region=36 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  60%|█████▉    | 347/580 [06:24<03:39,  1.06it/s]

ERROR region=36 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  60%|██████    | 348/580 [06:25<03:32,  1.09it/s]

ERROR region=36 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  60%|██████    | 349/580 [06:26<03:22,  1.14it/s]

ERROR region=36 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  60%|██████    | 350/580 [06:27<03:16,  1.17it/s]

ERROR region=36 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  61%|██████    | 351/580 [06:27<02:55,  1.31it/s]

ERROR region=37 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  61%|██████    | 352/580 [06:28<02:40,  1.42it/s]

ERROR region=37 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  61%|██████    | 353/580 [06:29<02:48,  1.35it/s]

ERROR region=37 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  61%|██████    | 354/580 [06:30<02:52,  1.31it/s]

ERROR region=37 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  61%|██████    | 355/580 [06:30<02:57,  1.27it/s]

ERROR region=37 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  62%|██████▏   | 357/580 [06:32<02:51,  1.30it/s]

ERROR region=37 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  62%|██████▏   | 358/580 [06:33<02:54,  1.27it/s]

ERROR region=37 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  62%|██████▏   | 359/580 [06:34<02:55,  1.26it/s]

ERROR region=37 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  62%|██████▏   | 360/580 [06:35<03:00,  1.22it/s]

ERROR region=37 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  62%|██████▏   | 362/580 [06:36<03:09,  1.15it/s]

ERROR region=38 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  63%|██████▎   | 363/580 [06:37<03:05,  1.17it/s]

ERROR region=38 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  63%|██████▎   | 364/580 [06:38<03:08,  1.15it/s]

ERROR region=38 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  63%|██████▎   | 365/580 [06:39<03:04,  1.16it/s]

ERROR region=38 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  63%|██████▎   | 367/580 [06:41<03:10,  1.12it/s]

ERROR region=38 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  63%|██████▎   | 368/580 [06:42<03:08,  1.12it/s]

ERROR region=38 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  64%|██████▎   | 369/580 [06:43<03:04,  1.14it/s]

ERROR region=38 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  64%|██████▍   | 370/580 [06:43<03:02,  1.15it/s]

ERROR region=38 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  64%|██████▍   | 371/580 [06:44<03:00,  1.16it/s]

ERROR region=39 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  64%|██████▍   | 372/580 [06:45<02:59,  1.16it/s]

ERROR region=39 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  64%|██████▍   | 373/580 [06:46<02:56,  1.17it/s]

ERROR region=39 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  64%|██████▍   | 374/580 [06:47<02:52,  1.19it/s]

ERROR region=39 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  65%|██████▍   | 375/580 [06:48<02:51,  1.20it/s]

ERROR region=39 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  65%|██████▌   | 377/580 [06:50<02:59,  1.13it/s]

ERROR region=39 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  65%|██████▌   | 378/580 [06:50<02:54,  1.15it/s]

ERROR region=39 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  65%|██████▌   | 379/580 [06:51<02:50,  1.18it/s]

ERROR region=39 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  66%|██████▌   | 380/580 [06:52<02:46,  1.20it/s]

ERROR region=39 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  66%|██████▌   | 381/580 [06:53<02:44,  1.21it/s]

ERROR region=40 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  66%|██████▌   | 382/580 [06:53<02:28,  1.33it/s]

ERROR region=40 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  66%|██████▌   | 383/580 [06:54<02:16,  1.44it/s]

ERROR region=40 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  66%|██████▌   | 384/580 [06:54<02:08,  1.53it/s]

ERROR region=40 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  66%|██████▋   | 385/580 [06:55<02:16,  1.42it/s]

ERROR region=40 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  67%|██████▋   | 387/580 [06:57<02:37,  1.23it/s]

ERROR region=40 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  67%|██████▋   | 388/580 [06:58<02:39,  1.20it/s]

ERROR region=40 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  67%|██████▋   | 389/580 [06:59<02:38,  1.21it/s]

ERROR region=40 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  67%|██████▋   | 390/580 [06:59<02:21,  1.34it/s]

ERROR region=40 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  67%|██████▋   | 391/580 [07:00<02:09,  1.46it/s]

ERROR region=41 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  68%|██████▊   | 392/580 [07:01<02:16,  1.38it/s]

ERROR region=41 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  68%|██████▊   | 393/580 [07:02<02:26,  1.28it/s]

ERROR region=41 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  68%|██████▊   | 394/580 [07:03<02:29,  1.25it/s]

ERROR region=41 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  68%|██████▊   | 395/580 [07:03<02:31,  1.22it/s]

ERROR region=41 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  68%|██████▊   | 397/580 [07:05<02:45,  1.11it/s]

ERROR region=41 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  69%|██████▊   | 398/580 [07:06<02:41,  1.13it/s]

ERROR region=41 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  69%|██████▉   | 399/580 [07:07<02:37,  1.15it/s]

ERROR region=41 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  69%|██████▉   | 400/580 [07:08<02:37,  1.15it/s]

ERROR region=41 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  69%|██████▉   | 401/580 [07:09<02:34,  1.16it/s]

ERROR region=42 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  69%|██████▉   | 402/580 [07:10<02:31,  1.18it/s]

ERROR region=42 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  69%|██████▉   | 403/580 [07:10<02:29,  1.19it/s]

ERROR region=42 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  70%|██████▉   | 404/580 [07:11<02:28,  1.18it/s]

ERROR region=42 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  70%|██████▉   | 405/580 [07:12<02:27,  1.18it/s]

ERROR region=42 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  70%|███████   | 407/580 [07:14<02:33,  1.13it/s]

ERROR region=42 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  70%|███████   | 408/580 [07:15<02:29,  1.15it/s]

ERROR region=42 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  71%|███████   | 409/580 [07:16<02:25,  1.18it/s]

ERROR region=42 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  71%|███████   | 410/580 [07:16<02:08,  1.33it/s]

ERROR region=42 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  71%|███████   | 411/580 [07:17<02:11,  1.28it/s]

ERROR region=43 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  71%|███████   | 412/580 [07:18<02:13,  1.26it/s]

ERROR region=43 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  71%|███████   | 413/580 [07:19<02:14,  1.24it/s]

ERROR region=43 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  71%|███████▏  | 414/580 [07:20<02:15,  1.23it/s]

ERROR region=43 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  72%|███████▏  | 415/580 [07:20<02:19,  1.19it/s]

ERROR region=43 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  72%|███████▏  | 417/580 [07:22<02:09,  1.26it/s]

ERROR region=43 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  72%|███████▏  | 418/580 [07:23<02:00,  1.35it/s]

ERROR region=43 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  72%|███████▏  | 419/580 [07:24<02:06,  1.28it/s]

ERROR region=43 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  72%|███████▏  | 420/580 [07:24<02:10,  1.23it/s]

ERROR region=43 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  73%|███████▎  | 421/580 [07:26<02:22,  1.12it/s]

ERROR region=44 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  73%|███████▎  | 422/580 [07:26<02:17,  1.15it/s]

ERROR region=44 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  73%|███████▎  | 423/580 [07:27<02:14,  1.17it/s]

ERROR region=44 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  73%|███████▎  | 424/580 [07:28<02:12,  1.18it/s]

ERROR region=44 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  73%|███████▎  | 425/580 [07:29<02:11,  1.18it/s]

ERROR region=44 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  74%|███████▎  | 427/580 [07:31<02:14,  1.14it/s]

ERROR region=44 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  74%|███████▍  | 428/580 [07:32<02:11,  1.16it/s]

ERROR region=44 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  74%|███████▍  | 429/580 [07:32<02:09,  1.16it/s]

ERROR region=44 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  74%|███████▍  | 430/580 [07:33<02:08,  1.17it/s]

ERROR region=44 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  74%|███████▍  | 431/580 [07:34<01:53,  1.31it/s]

ERROR region=45 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  74%|███████▍  | 432/580 [07:35<01:56,  1.27it/s]

ERROR region=45 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  75%|███████▍  | 433/580 [07:35<01:56,  1.27it/s]

ERROR region=45 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  75%|███████▍  | 434/580 [07:36<01:56,  1.25it/s]

ERROR region=45 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  75%|███████▌  | 435/580 [07:37<02:00,  1.21it/s]

ERROR region=45 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  75%|███████▌  | 437/580 [07:39<02:05,  1.14it/s]

ERROR region=45 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  76%|███████▌  | 438/580 [07:40<02:04,  1.14it/s]

ERROR region=45 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  76%|███████▌  | 439/580 [07:41<02:02,  1.15it/s]

ERROR region=45 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  76%|███████▌  | 440/580 [07:41<01:47,  1.30it/s]

ERROR region=45 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  76%|███████▌  | 441/580 [07:42<01:49,  1.27it/s]

ERROR region=46 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  76%|███████▌  | 442/580 [07:43<01:49,  1.26it/s]

ERROR region=46 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  76%|███████▋  | 443/580 [07:44<01:49,  1.25it/s]

ERROR region=46 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  77%|███████▋  | 444/580 [07:45<01:58,  1.15it/s]

ERROR region=46 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  77%|███████▋  | 445/580 [07:46<02:07,  1.06it/s]

ERROR region=46 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  77%|███████▋  | 447/580 [07:48<02:04,  1.07it/s]

ERROR region=46 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  77%|███████▋  | 448/580 [07:49<02:08,  1.03it/s]

ERROR region=46 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  77%|███████▋  | 449/580 [07:50<02:06,  1.03it/s]

ERROR region=46 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  78%|███████▊  | 450/580 [07:51<02:01,  1.07it/s]

ERROR region=46 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  78%|███████▊  | 452/580 [07:53<02:04,  1.03it/s]

ERROR region=47 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  78%|███████▊  | 453/580 [07:54<01:58,  1.07it/s]

ERROR region=47 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  78%|███████▊  | 454/580 [07:54<01:53,  1.11it/s]

ERROR region=47 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  78%|███████▊  | 455/580 [07:55<01:52,  1.12it/s]

ERROR region=47 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  79%|███████▉  | 457/580 [07:57<01:56,  1.06it/s]

ERROR region=47 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  79%|███████▉  | 458/580 [07:58<01:51,  1.09it/s]

ERROR region=47 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  79%|███████▉  | 459/580 [07:59<01:37,  1.25it/s]

ERROR region=47 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  79%|███████▉  | 460/580 [08:00<01:37,  1.24it/s]

ERROR region=47 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  80%|███████▉  | 462/580 [08:02<01:44,  1.13it/s]

ERROR region=48 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  80%|███████▉  | 463/580 [08:02<01:41,  1.15it/s]

ERROR region=48 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  80%|████████  | 464/580 [08:03<01:39,  1.17it/s]

ERROR region=48 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  80%|████████  | 465/580 [08:04<01:27,  1.32it/s]

ERROR region=48 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  81%|████████  | 467/580 [08:06<01:37,  1.16it/s]

ERROR region=48 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  81%|████████  | 468/580 [08:07<01:36,  1.16it/s]

ERROR region=48 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  81%|████████  | 469/580 [08:07<01:26,  1.28it/s]

ERROR region=48 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  81%|████████  | 470/580 [08:08<01:32,  1.19it/s]

ERROR region=48 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  81%|████████▏ | 472/580 [08:10<01:35,  1.13it/s]

ERROR region=49 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  82%|████████▏ | 473/580 [08:11<01:33,  1.15it/s]

ERROR region=49 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  82%|████████▏ | 474/580 [08:12<01:31,  1.16it/s]

ERROR region=49 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  82%|████████▏ | 475/580 [08:13<01:30,  1.16it/s]

ERROR region=49 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  82%|████████▏ | 477/580 [08:14<01:32,  1.11it/s]

ERROR region=49 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  82%|████████▏ | 478/580 [08:15<01:29,  1.14it/s]

ERROR region=49 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  83%|████████▎ | 479/580 [08:16<01:27,  1.15it/s]

ERROR region=49 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  83%|████████▎ | 480/580 [08:17<01:25,  1.17it/s]

ERROR region=49 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  83%|████████▎ | 482/580 [08:19<01:27,  1.12it/s]

ERROR region=50 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  83%|████████▎ | 483/580 [08:20<01:24,  1.14it/s]

ERROR region=50 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  83%|████████▎ | 484/580 [08:21<01:22,  1.16it/s]

ERROR region=50 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  84%|████████▎ | 485/580 [08:21<01:21,  1.17it/s]

ERROR region=50 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  84%|████████▍ | 487/580 [08:23<01:21,  1.14it/s]

ERROR region=50 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  84%|████████▍ | 488/580 [08:24<01:19,  1.16it/s]

ERROR region=50 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  84%|████████▍ | 489/580 [08:25<01:17,  1.18it/s]

ERROR region=50 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  84%|████████▍ | 490/580 [08:26<01:15,  1.19it/s]

ERROR region=50 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  85%|████████▍ | 492/580 [08:28<01:17,  1.13it/s]

ERROR region=51 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  85%|████████▌ | 493/580 [08:28<01:07,  1.28it/s]

ERROR region=51 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  85%|████████▌ | 494/580 [08:29<01:08,  1.26it/s]

ERROR region=51 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  85%|████████▌ | 495/580 [08:30<01:08,  1.25it/s]

ERROR region=51 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  86%|████████▌ | 497/580 [08:32<01:11,  1.15it/s]

ERROR region=51 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  86%|████████▌ | 498/580 [08:32<01:09,  1.18it/s]

ERROR region=51 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  86%|████████▌ | 499/580 [08:33<01:07,  1.20it/s]

ERROR region=51 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  86%|████████▌ | 500/580 [08:34<01:06,  1.20it/s]

ERROR region=51 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  87%|████████▋ | 502/580 [08:36<01:09,  1.13it/s]

ERROR region=52 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  87%|████████▋ | 503/580 [08:37<01:11,  1.08it/s]

ERROR region=52 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  87%|████████▋ | 504/580 [08:38<01:12,  1.05it/s]

ERROR region=52 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  87%|████████▋ | 505/580 [08:39<01:16,  1.01s/it]

ERROR region=52 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  87%|████████▋ | 507/580 [08:41<01:12,  1.01it/s]

ERROR region=52 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  88%|████████▊ | 508/580 [08:42<01:08,  1.05it/s]

ERROR region=52 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  88%|████████▊ | 509/580 [08:43<01:05,  1.09it/s]

ERROR region=52 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  88%|████████▊ | 510/580 [08:44<01:03,  1.11it/s]

ERROR region=52 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  88%|████████▊ | 511/580 [08:45<01:02,  1.10it/s]

ERROR region=53 tipo=1 dorm=1 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  88%|████████▊ | 512/580 [08:46<01:00,  1.12it/s]

ERROR region=53 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  88%|████████▊ | 513/580 [08:46<00:57,  1.16it/s]

ERROR region=53 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  89%|████████▊ | 514/580 [08:47<00:56,  1.17it/s]

ERROR region=53 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  89%|████████▉ | 515/580 [08:48<00:54,  1.19it/s]

ERROR region=53 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  89%|████████▉ | 517/580 [08:50<00:55,  1.13it/s]

ERROR region=53 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  89%|████████▉ | 518/580 [08:51<00:53,  1.15it/s]

ERROR region=53 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  89%|████████▉ | 519/580 [08:52<00:52,  1.16it/s]

ERROR region=53 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  90%|████████▉ | 520/580 [08:52<00:51,  1.16it/s]

ERROR region=53 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  90%|█████████ | 522/580 [08:54<00:51,  1.13it/s]

ERROR region=54 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  90%|█████████ | 523/580 [08:55<00:49,  1.15it/s]

ERROR region=54 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  90%|█████████ | 524/580 [08:56<00:48,  1.17it/s]

ERROR region=54 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  91%|█████████ | 525/580 [08:57<00:47,  1.16it/s]

ERROR region=54 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  91%|█████████ | 527/580 [08:59<00:47,  1.12it/s]

ERROR region=54 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  91%|█████████ | 528/580 [09:00<00:45,  1.14it/s]

ERROR region=54 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  91%|█████████ | 529/580 [09:00<00:44,  1.15it/s]

ERROR region=54 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  91%|█████████▏| 530/580 [09:01<00:42,  1.17it/s]

ERROR region=54 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  92%|█████████▏| 532/580 [09:03<00:42,  1.12it/s]

ERROR region=55 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  92%|█████████▏| 533/580 [09:04<00:40,  1.15it/s]

ERROR region=55 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  92%|█████████▏| 534/580 [09:05<00:39,  1.15it/s]

ERROR region=55 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  92%|█████████▏| 535/580 [09:05<00:34,  1.29it/s]

ERROR region=55 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  93%|█████████▎| 537/580 [09:07<00:36,  1.17it/s]

ERROR region=55 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  93%|█████████▎| 538/580 [09:09<00:42,  1.01s/it]

ERROR region=55 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  93%|█████████▎| 539/580 [09:10<00:40,  1.02it/s]

ERROR region=55 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  93%|█████████▎| 540/580 [09:10<00:34,  1.17it/s]

ERROR region=55 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  93%|█████████▎| 542/580 [09:12<00:31,  1.21it/s]

ERROR region=56 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  94%|█████████▎| 543/580 [09:13<00:30,  1.20it/s]

ERROR region=56 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  94%|█████████▍| 544/580 [09:14<00:29,  1.21it/s]

ERROR region=56 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  94%|█████████▍| 545/580 [09:14<00:28,  1.21it/s]

ERROR region=56 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  94%|█████████▍| 547/580 [09:16<00:29,  1.13it/s]

ERROR region=56 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  94%|█████████▍| 548/580 [09:17<00:25,  1.28it/s]

ERROR region=56 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  95%|█████████▍| 549/580 [09:18<00:24,  1.25it/s]

ERROR region=56 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  95%|█████████▍| 550/580 [09:18<00:24,  1.23it/s]

ERROR region=56 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  95%|█████████▌| 552/580 [09:20<00:24,  1.15it/s]

ERROR region=57 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  95%|█████████▌| 553/580 [09:21<00:23,  1.16it/s]

ERROR region=57 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  96%|█████████▌| 554/580 [09:22<00:22,  1.18it/s]

ERROR region=57 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  96%|█████████▌| 555/580 [09:23<00:21,  1.19it/s]

ERROR region=57 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  96%|█████████▌| 557/580 [09:25<00:20,  1.13it/s]

ERROR region=57 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  96%|█████████▌| 558/580 [09:26<00:19,  1.16it/s]

ERROR region=57 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  96%|█████████▋| 559/580 [09:26<00:16,  1.29it/s]

ERROR region=57 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  97%|█████████▋| 560/580 [09:27<00:15,  1.26it/s]

ERROR region=57 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  97%|█████████▋| 562/580 [09:29<00:17,  1.06it/s]

ERROR region=58 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  97%|█████████▋| 563/580 [09:30<00:15,  1.11it/s]

ERROR region=58 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  97%|█████████▋| 564/580 [09:31<00:14,  1.13it/s]

ERROR region=58 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  97%|█████████▋| 565/580 [09:32<00:13,  1.13it/s]

ERROR region=58 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  98%|█████████▊| 567/580 [09:34<00:11,  1.12it/s]

ERROR region=58 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  98%|█████████▊| 568/580 [09:34<00:10,  1.15it/s]

ERROR region=58 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  98%|█████████▊| 569/580 [09:35<00:09,  1.17it/s]

ERROR region=58 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  98%|█████████▊| 570/580 [09:36<00:08,  1.17it/s]

ERROR region=58 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  99%|█████████▊| 572/580 [09:38<00:07,  1.11it/s]

ERROR region=59 tipo=1 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  99%|█████████▉| 573/580 [09:39<00:05,  1.27it/s]

ERROR region=59 tipo=1 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  99%|█████████▉| 574/580 [09:39<00:04,  1.26it/s]

ERROR region=59 tipo=1 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  99%|█████████▉| 575/580 [09:40<00:04,  1.24it/s]

ERROR region=59 tipo=1 dorm=5 -> If using all scalar values, you must pass an index

Downloading FIPEZAP:  99%|█████████▉| 577/580 [09:42<00:02,  1.15it/s]

ERROR region=59 tipo=2 dorm=2 -> If using all scalar values, you must pass an index

Downloading FIPEZAP: 100%|█████████▉| 578/580 [09:43<00:01,  1.17it/s]

ERROR region=59 tipo=2 dorm=3 -> If using all scalar values, you must pass an index

Downloading FIPEZAP: 100%|█████████▉| 579/580 [09:44<00:00,  1.18it/s]

ERROR region=59 tipo=2 dorm=4 -> If using all scalar values, you must pass an index

Downloading FIPEZAP: 100%|██████████| 580/580 [09:44<00:00,  1.01s/it]

ERROR region=59 tipo=2 dorm=5 -> If using all scalar values, you must pass an index

Errores totales: 333

,date,country,region_code,city,rooms,variable,value,var_type,source
0,2026-02-01,Brazil,2,São Paulo,total,price_rent_index,241.25063,index,FIPEZAP
1,2026-01-01,Brazil,2,São Paulo,total,price_rent_index,240.02878,index,FIPEZAP
2,2025-12-01,Brazil,2,São Paulo,total,price_rent_index,239.00537,index,FIPEZAP
3,2025-11-01,Brazil,2,São Paulo,total,price_rent_index,237.83917,index,FIPEZAP
4,2025-10-01,Brazil,2,São Paulo,total,price_rent_index,236.52854,index,FIPEZAP

In [161]:
df_fipezap["base_year"]=2010
df_fipezap

,date,country,region_code,city,rooms,variable,value,var_type,source,base_year
0,2026-02-01,Brazil,2,São Paulo,total,price_rent_index,241.25063,index,FIPEZAP,2010
1,2026-01-01,Brazil,2,São Paulo,total,price_rent_index,240.02878,index,FIPEZAP,2010
2,2025-12-01,Brazil,2,São Paulo,total,price_rent_index,239.00537,index,FIPEZAP,2010
3,2025-11-01,Brazil,2,São Paulo,total,price_rent_index,237.83917,index,FIPEZAP,2010
4,2025-10-01,Brazil,2,São Paulo,total,price_rent_index,236.52854,index,FIPEZAP,2010
...,...,...,...,...,...,...,...,...,...,...
28620,2022-05-01,Brazil,59,Belém,total,price_sale_index,98.31647,index,FIPEZAP,2010
28621,2022-04-01,Brazil,59,Belém,total,price_sale_index,99.09569,index,FIPEZAP,2010
28622,2022-03-01,Brazil,59,Belém,total,price_sale_index,100.08294,index,FIPEZAP,2010
28623,2022-02-01,Brazil,59,Belém,total,price_sale_index,100.66682,index,FIPEZAP,2010
28624,2022-01-01,Brazil,59,Belém,total,price_sale_index,100.00000,index,FIPEZAP,2010

In [137]:
url="https://www.fipe.org.br/IndicesConsulta-FipeZapPesquisa?tipo=1&regiao=28&info=2&dormitorio=5"

response = requests.get(url, headers=headers)
print(response.status_code)
data=pd.DataFrame(response.json())
data

200

,Ano,Mes,CodigoDormitorio,FipeZap Locação,FipeZap Locação_VariacaoUltimos12Meses
0,2026,2,5,259.267830,8.967574
1,2026,1,5,257.402410,9.897506
2,2025,12,5,254.112660,9.640962
3,2025,11,5,250.545210,9.229440
4,2025,10,5,248.215600,9.370148
...,...,...,...,...,...
129,2015,5,5,146.837009,-2.922848
130,2015,4,5,147.590304,-3.289859
131,2015,3,5,146.977171,-3.665003
132,2015,2,5,147.322498,-2.592887
133,2015,1,5,147.040457,-2.383035

In [168]:
#Paste all dataframes together
indices_vivienda=pd.concat([tabla_ipv, ipvu,shf,df_fipezap], ignore_index=True)
#Save to csv
indices_vivienda.to_csv("housing_indexes.csv",encoding="latin1", index=False)
indices_vivienda

,date,variable,value,country,source,base_year,var_type,index,state,municipality,region_code,city,rooms
0,2002-01-01 00:00:00,ipv_general,79.819860,Chile,Banco Central de Chile,2008,index,NaN,NaN,NaN,NaN,NaN,NaN
1,2002-04-01 00:00:00,ipv_general,82.868177,Chile,Banco Central de Chile,2008,index,NaN,NaN,NaN,NaN,NaN,NaN
2,2002-07-01 00:00:00,ipv_general,83.698377,Chile,Banco Central de Chile,2008,index,NaN,NaN,NaN,NaN,NaN,NaN
3,2002-10-01 00:00:00,ipv_general,83.196206,Chile,Banco Central de Chile,2008,index,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-01-01 00:00:00,ipv_general,82.737826,Chile,Banco Central de Chile,2008,index,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40131,2022-05-01 00:00:00,price_sale_index,98.316470,Brazil,FIPEZAP,2010,index,NaN,NaN,NaN,59.0,Belém,total
40132,2022-04-01 00:00:00,price_sale_index,99.095690,Brazil,FIPEZAP,2010,index,NaN,NaN,NaN,59.0,Belém,total
40133,2022-03-01 00:00:00,price_sale_index,100.082940,Brazil,FIPEZAP,2010,index,NaN,NaN,NaN,59.0,Belém,total
40134,2022-02-01 00:00:00,price_sale_index,100.666820,Brazil,FIPEZAP,2010,index,NaN,NaN,NaN,59.0,Belém,total
40135,2022-01-01 00:00:00,price_sale_index,100.000000,Brazil,FIPEZAP,2010,index,NaN,NaN,NaN,59.0,Belém,total

### Río de Janeiro (Brazil)

In [171]:
base_url = "https://pgeo3.rio.rj.gov.br/arcgis/rest/services/Fazenda/ITBI/MapServer/3/query"

params = {
    "where": "1=1",
    "outFields": "*",
    "outSR": 4326,
    "f": "json",
    "resultRecordCount": 1000  
}

todos = []
offset = 0

while True:
    params["resultOffset"] = offset
    
    r = requests.get(base_url, params=params)
    data = r.json()
    
    features = data.get("features", [])
    
    if not features:
        break
    
    todos.extend([f["attributes"] for f in features])
    

    if not data.get("exceededTransferLimit", False):
        break
    
    offset += 1000

rio = pd.DataFrame(todos)
rio["source"] = "Prefeitura da Cidade do Rio de Janeiro"
rio.to_csv("transactions_riodejaneiro.csv",encoding="latin1",index=False)
rio

,objectid,cl,logradouro,codbairro,bairro,total_transações,uso,média_percentual_transferido,média_área_terreno,média_valor_transação,média_valor_imóvel,principal_transação_mercado,ano_transação,source
0,1328978,126680,RUA CHOVE LA FORA,151,Guaratiba,2,TERRITORIAL,100.0,300.0,26136.010000,26136.010000,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
1,1328979,135830,RUA ENRICO CARUSO,151,Guaratiba,2,TERRITORIAL,100.0,360.0,64745.990000,64745.990000,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
2,1328980,136028,RUA TORRE DE PEDRA,151,Guaratiba,2,TERRITORIAL,75.0,345.0,51107.765000,65957.770000,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
3,1328981,136036,RUA VARGEM DO CEDRO,151,Guaratiba,2,TERRITORIAL,100.0,375.0,77932.790000,77932.790000,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
4,1328982,225391,RUA FRANCISCO MIGNONE,151,Guaratiba,3,TERRITORIAL,100.0,416.0,167867.376666,167867.376666,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4735,1333713,033431,ETR DA PACIENCIA,148,Paciência,2,TERRITORIAL,100.0,297.0,46935.885000,46935.885000,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
4736,1333714,001008,RUA D-2 PAL 19600,151,Guaratiba,3,TERRITORIAL,100.0,360.0,51811.213333,51811.213333,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
4737,1333715,031286,ETR DA MATRIZ,151,Guaratiba,5,TERRITORIAL,100.0,5012.0,286526.596000,286526.596000,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
4738,1333716,125773,RUA LUIZ BRUNINI (RADIALISTA),151,Guaratiba,3,TERRITORIAL,100.0,300.0,27181.440000,27181.440000,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro
4739,1333717,125997,RUA ABDIAS DO NASCIMENTO (SENADOR),151,Guaratiba,2,TERRITORIAL,100.0,323.0,35426.165000,35426.165000,COMPRA E VENDA,2021,Prefeitura da Cidade do Rio de Janeiro